1

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,14 +34,11 @@ jobs:
 
       - name: 🔍 Debug build outputs
         run: |
-          echo "Current folder:"
-          pwd
-          echo "Contents:"
-          ls -al
-          echo "Dist contents:"
-          ls -al dist || echo "⚠️ dist/ not found"
+          echo "Current folder:" && pwd
+          echo "Contents:" && ls -al
+          echo "Dist contents:" && ls -al dist || echo "⚠️ dist/ not found"
 
-        - name: 📤 Upload to EC2 (only dist & package files)
+      - name: 📤 Upload to EC2 (only dist & package files)
         uses: appleboy/scp-action@master
         with:
           host: ${{ secrets.EC2_HOST }}
@@ -50,7 +47,6 @@ jobs:
           source: dist/**,package.json,package-lock.json,docker-compose.uat.yml,Dockerfile.runtime
           target: /home/ubuntu/deploy/dispatch-backend
           strip_components: 0
-
 
       - name: 🔁 Restart service on EC2
         uses: appleboy/ssh-action@master
